CREATE TABLE BOARD (
  seq         INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title     VARCHAR(255) NOT NULL ,
  content     VARCHAR(1000) NOT NULL ,
  writer     VARCHAR(10) NOT NULL ,
  password    INT NOT NULL ,
  regDate     TIMESTAMP NOT NULL ,
  cnt         INT DEFAULT 0 NOT NULL 
);

CREATE TABLE EXCHANGE (
	seq			INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	stdRate 	DOUBLE NOT NULL,
	regDate 	VARCHAR(30) NOT NULL,
	variation 	DOUBLE NOT NULL
	
);

CREATE TABLE KOSPI (
	seq			INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	endPrice 	DOUBLE NOT NULL,
	regDate 	VARCHAR(30) NOT NULL,
	variation 	DOUBLE NOT NULL
	
);

CREATE TABLE FOREIGNSELL (
	seq				INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	retail 	    	INT NOT NULL,
	regDate 		VARCHAR(30) NOT NULL,
	foreigns 		INT NOT NULL,
	institutional 	INT NOT NULL
	
);